# Generated by Django 5.1.3 on 2024-11-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True)),  # Use a string-based ID
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('ingredients', models.JSONField()),  # Keep JSONField as it will work with PyMongo
                ('instructions', models.JSONField()),  # Same for instructions
            ],
        ),
    ]
