# Generated by Django 5.1.3 on 2024-11-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tekk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('ingredients', models.JSONField()),
                ('instructions', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
